FROM python:3.9-slim

WORKDIR /app

COPY requirements/backend.txt .
RUN pip install --no-cache-dir -r backend.txt

COPY backend/ .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]